### ISSUE TITLE
[Feature] 주식 추천 상위 10개 조회 API 구현

### ISSUE THREAD

**Issue by hosunglee222** [hosunglee222/stock-data-analysis#1]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 모델링된 데이터 중 오늘의 상위 10개 종목을 제공합니다.

## **Todo**

- [ ] 상위 10개 조회
